import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, CalendarDays, Check, ChevronDown, ChevronRight, MapPin, MessageCircle, Plus, Ticket, ThumbsUp, X } from 'lucide-react';
import { Wordmark, RallyIcon, DesignPhoto } from './Design.jsx';
import EveningView from './EveningView.jsx';
import './frosted.css';

export default function GuestPage({ state, onAction, busy, error, renderArt, onBack }) {
  const [tab,setTab]=useState('page'),[success,setSuccess]=useState(null),[offer,setOffer]=useState(true),[suggesting,setSuggesting]=useState(false),[idea,setIdea]=useState(''),[reason,setReason]=useState(''),[text,setText]=useState(''),[notice,setNotice]=useState('');
  const successHeading=useRef(null), plan=state.plan, person=plan.participants.find(p=>p.id===state.guestId), events=state.events;
  useEffect(()=>{if(success)successHeading.current?.focus();},[success]);
  const closed=['happened','dropped'].includes(plan.status);
  async function respond(response) { if(await onAction('rsvp',{response})) {setSuccess('Your reply has been saved!');setOffer(true);} }
  const art=e=>e.image?<img className="event-photo" src={e.image} alt="" loading="lazy"/>:['comedy','dinner','rooftop'].includes(e.color)?<DesignPhoto kind={e.color}/>:renderArt(e.color);
  const badge=<span className={`status ${plan.status}`}>{({proposed:'A plan in the making',confirmed:'It’s happening',happened:'One for the memories',dropped:'Plan closed'})[plan.status]}</span>;
  const signup=<a className="signup-banner" href="/"><RallyIcon/><span><strong>Sign up for Rall-e now!</strong><small>Rall-e plans your social life so you can focus on the fun stuff</small></span><ChevronRight size={22}/></a>;
  if(success) return <main className="vote-success"><header><a href="/" aria-label="Rall-e home"><Wordmark/></a><button className="icon-button" aria-label="Back to plan" onClick={()=>setSuccess(null)}><X/></button></header><section className="vote-success-message"><div className="success-check"><Check strokeWidth={2}/></div><h1 ref={successHeading} tabIndex={-1}>{success}</h1><p>{person?.name}, {state.name}’s plan is up to date.</p><button className="button success-back" onClick={()=>setSuccess(null)}>Back to the plan</button></section>{offer?<section className="signup-sheet"><button className="icon-button" aria-label="Dismiss Rall-e invitation" onClick={()=>setOffer(false)}><X/></button><RallyIcon/><h2>Sign up for Rall-e now!</h2><p>Rall-e plans your social life so you<br/>can focus on the fun stuff</p><a className="button primary" href="/">Try Rall-e <ChevronRight size={17}/></a><button className="text-link" onClick={()=>{setOffer(false);setSuccess(null);}}>Not now</button></section>:signup}</main>;
  return <main className="guest-experience"><header className="guest-header"><a href="/" aria-label="Rall-e home"><Wordmark/></a>{onBack?<button className="text-link" onClick={onBack}><ArrowLeft size={15}/>Host view</button>:<span>A PLAN FROM {state.name.toUpperCase()}</span>}</header><div className="guest-intro"><h1>{state.name} has a plan for you.</h1><p>Good company. One shared page. You’re invited.</p></div><nav className="guest-tabs" role="tablist" aria-label="Plan views"><button role="tab" aria-selected={tab==='page'} onClick={()=>setTab('page')}>The page</button><button role="tab" aria-selected={tab==='chat'} onClick={()=>setTab('chat')}><MessageCircle size={15}/>Texts</button></nav>{error&&<p role="alert" className="error">{error}</p>}
    {tab==='chat'?<section className="guest-chat"><header><RallyIcon/><div><strong>Your texts with Rall-e</strong><small>Interactive preview · no text sent</small></div></header><div className="message assistant"><div className="bubble">Hey {person.name}! {state.name} has a plan for {plan.title}. Are you in?</div></div>{plan.stops.map(id=>{const e=events.find(x=>x.id===id);return <button key={id} className="sms-event-preview" onClick={()=>setTab('page')}>{art(e)}<strong>{e.short}</strong><span>{e.time}</span></button>;})}<p className="fine">On-screen replies are simulated and update the shared plan.</p><div className="quick-replies">{['YES','MAYBE','NO'].map(value=><button key={value} disabled={busy||closed||person.stopped} onClick={async()=>{if(await onAction('text',{text:value}))setNotice('Reply simulated. Your plan is up to date.');}}>{value}</button>)}</div><form className="guest-text-form" onSubmit={async e=>{e.preventDefault();if(await onAction('text',{text:text.trim()})){setNotice(/^help$/i.test(text)?'Reply YES, MAYBE, NO or STOP. This is an on-screen simulation.':'Reply simulated. Your plan is up to date.');setText('');}}}><input aria-label="Simulate text reply" placeholder="YES, MAYBE, NO, STOP, HELP" value={text} onChange={e=>setText(e.target.value)}/><button className="button primary" disabled={busy||!text.trim()}>Send</button></form>{notice&&<p role="status">{notice}</p>}</section>:<div className="guest-plan-layout"><div className="guest-event-column"><EveningView state={state} meId={person.id} busy={busy} renderArt={renderArt} onRsvp={respond} onVote={id=>onAction('vote',{id})} shareUrl={state.shareUrl} textNumbers={state.textNumbers}/></div>
      <aside className="guest-details-column"><section className="guest-detail-card"><h2>The good company</h2>{plan.participants.map(p=><div className="person-row" key={p.id}><span className="avatar">{p.name.slice(0,1)}</span><span><strong>{p.name}{p.id===person.id?' (you)':''}</strong></span><span className={`rsvp-status ${p.response}`}>{({yes:'I’m in',maybe:'Maybe',no:'Can’t make it',pending:'Awaiting reply'})[p.response]}</span></div>)}<GuestTexts on={state.texting} stopped={person.stopped} host={state.name}/></section>
      {plan.mode==='loose'&&<section className="guest-detail-card"><h2>A little room for other ideas</h2><p>Got a different spot in mind? Put an idea to the group.</p>{plan.status==='proposed'&&<button className="button secondary full" onClick={()=>{setIdea(events.find(e=>!plan.stops.includes(e.id))?.id||'');setSuggesting(!suggesting);}}><Plus size={16}/>Suggest another idea</button>}
      {suggesting&&<form className="guest-suggest-form" onSubmit={async e=>{e.preventDefault();if(await onAction('suggest',{eventId:idea,reason})){setSuggesting(false);setReason('');}}}><label htmlFor="guest-idea">Your idea</label><select id="guest-idea" value={idea} onChange={e=>setIdea(e.target.value)}>{events.filter(e=>!plan.stops.includes(e.id)).map(e=><option value={e.id} key={e.id}>{e.short}</option>)}</select><div className="guest-option-gallery">{events.filter(e=>!plan.stops.includes(e.id)).map(e=><button type="button" className={`guest-option-card ${idea===e.id?'selected':''}`} key={e.id} aria-label={`Pick ${e.short}`} aria-pressed={idea===e.id} onClick={()=>setIdea(e.id)}>{art(e)}<div><h3>{e.short}</h3><p>{e.venue} · {e.time}</p><span>{e.priceText||(e.price?`Estimated cost $${e.price}`:'Free')}</span><strong><i>{idea===e.id&&<Check size={14}/>}</i>My pick</strong></div></button>)}</div><label htmlFor="guest-reason">A little pitch (optional)</label><textarea id="guest-reason" maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/><button className="button primary full" disabled={busy}>Put it to the group</button></form>}</section>}{signup}<p className="guest-footnote">Curated demo · Sample events and prices.<br/>Nothing is booked or purchased.</p></aside></div>}
  </main>;
}

// Turn on texts for this plan from the invite page: number + consent box, then the texted code (double opt-in).
const CONSENT = 'I agree to get texts from Rall-e about plans I make or join. Msg frequency varies. Msg & data rates may apply. Reply STOP to opt out, HELP for help.';
function GuestTexts({ on, stopped, host }) {
  const token = /^\/p\/([\w-]+)/.exec(location.pathname)?.[1];
  const [step, setStep] = useState(on ? 'done' : 'form'), [phone, setPhone] = useState(''), [consent, setConsent] = useState(false), [code, setCode] = useState(''), [demo, setDemo] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  if (!token) return null; // host preview of a guest page
  if (stopped) return <p className="guest-texts-note">You turned off Rall-e texts (STOP). Text START to Rall-e to turn them back on.</p>;
  const post = async (path, data) => { const r = await fetch(`/api/guest/${token}/${path}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }), d = await r.json(); if (!r.ok) throw new Error(d.error); return d; };
  const run = fn => async e => { e.preventDefault(); setBusy(true); setError(''); try { await fn(); } catch (x) { setError(x.message); } finally { setBusy(false); } };
  if (step === 'done') return <div className="guest-texts done"><Check size={16}/><span><strong>Texts are on</strong><small>Rall-e will text you when {host}’s plan changes. Reply to it anytime.</small></span></div>;
  return <form className="guest-texts" onSubmit={step === 'form' ? run(async () => { const r = await post('texts', { phone, consent }); setDemo(r.demoCode || ''); setStep('code'); }) : run(async () => { await post('texts/verify', { phone, code }); setStep('done'); })}>
    <strong>Get updates by text</strong>
    <small>Rall-e texts you when {host} changes the plan, and you can reply with questions or ideas.</small>
    {step === 'form' ? <>
      <input type="tel" autoComplete="tel" placeholder="Your mobile number" value={phone} onChange={e => setPhone(e.target.value)} required/>
      <label className="consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} required/><span>{CONSENT}</span></label>
      <button className="button primary full" disabled={busy || !consent}>Text me a code</button>
    </> : <>
      <small>We texted a 6-digit code to {phone}.{demo ? ` (Preview mode: ${demo})` : ''}</small>
      <input inputMode="numeric" autoComplete="one-time-code" placeholder="6-digit code" value={code} onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))} required/>
      <button className="button primary full" disabled={busy || code.length !== 6}>Turn on texts</button>
    </>}
    {error && <p role="alert" className="error">{error}</p>}
  </form>;
}
