import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUp, ArrowUpRight, ArrowRight, Check, ChevronDown, ChevronRight, Plus, MapPin, CalendarDays, Clock3, Users, MessageCircle, Sparkles, Settings2, X, Copy, Link, Bell, CheckCircle2, CircleHelp, Heart, Leaf, Music2, Utensils, Frame, RotateCcw, LockKeyhole, ThumbsUp, Send, Sun, Compass, ExternalLink, LoaderCircle } from 'lucide-react';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/dm-serif-display/latin-400.css';
import '@fontsource/dm-serif-display/latin-400-italic.css';
import './styles.css';
import SmsPanel from './SmsPanel.jsx';
import SmsLab from './SmsLab.jsx';
import VaultPage from './VaultPage.jsx';
import LocationPage from './LocationPage.jsx';
import EventPage from './EventPage.jsx';
import NightPage from './NightPage.jsx';
import SharePage from './SharePage.jsx';
import OpsPage from './OpsPage.jsx';
import { Wordmark, RallyIcon, DesignPhoto, Onboarding } from './Design.jsx';
import GuestPage from './GuestPage.jsx';
import MePage from './MePage.jsx';
import './figma.css';

const guestToken = /^\/p\/([\w-]+)/.exec(location.pathname)?.[1];
async function api(path, data) {
  const response = await fetch(path, data === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  const value = await response.json(); if (!response.ok) throw Object.assign(new Error(value.error), { status: response.status }); return value;
}
const vibeIcons = { dinner: Utensils, 'live shows': Music2, museums: Frame, nature: Leaf };
const initials = name => name.split(' ').map(x => x[0]).slice(0, 2).join('');
function Avatar({ name, index = 0, small = false }) { return <span className={`avatar avatar-${index % 4} ${small ? 'small' : ''}`}>{initials(name)}</span>; }
function Mark({ small = false }) { return <span className={`mark ${small ? 'small' : ''}`} aria-hidden="true"><RallyIcon/></span>; }
function Illustration({ kind = 'rooftop', className = '' }) {
  if (['comedy','dinner','rooftop'].includes(kind)) return <DesignPhoto kind={kind} className={className}/>;
  return <div className={`illustration ${kind} ${className}`} aria-hidden="true"><svg viewBox="0 0 640 350" preserveAspectRatio="xMidYMid slice">
    <defs><linearGradient id={`sky-${kind}`} x2="0" y2="1"><stop stopColor={kind === 'trail' ? '#d0d4a9' : kind === 'comedy' ? '#5c555f' : '#e6b195'}/><stop offset="1" stopColor={kind === 'trail' ? '#efdfb4' : kind === 'comedy' ? '#b87c75' : '#f5d8a6'}/></linearGradient><pattern id={`grain-${kind}`} width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#fff" opacity=".17"/></pattern></defs>
    <rect width="640" height="350" fill={`url(#sky-${kind})`}/><circle cx="440" cy="107" r="53" fill="#fff0bd" opacity=".9"/>
    {kind === 'trail' ? <><path d="M0 245 120 120 238 240 402 90 640 260V350H0" fill="#899278"/><path d="M0 310 240 170 400 310 550 215 640 270V350H0" fill="#485e50"/><path d="M285 350c-90-82 91-49 81-110 100 70-36 53-5 110" fill="#d3ba8b"/><path d="m86 273 18-101 18 101m400 45 24-143 24 143" fill="#2d4a3e"/></> : kind === 'museum' ? <><path d="M76 350V123l80-47h327l82 47v227" fill="#d6b497"/><path d="M115 350V152h410v198" fill="#efdbbe"/>{[155,275,395].map(x=><g key={x}><rect x={x} y="183" width="79" height="102" fill="#926853"/><rect x={x+8} y="191" width="63" height="86" fill="#c28f74"/><circle cx={x+40} cy="229" r="20" fill="#ead19f"/><path d={`M${x+8} 277l35-35 28 35`} fill="#697865"/></g>)}</> : kind === 'dinner' ? <><rect x="100" y="100" width="440" height="250" rx="70" fill="#b87961"/><path d="M138 350V175a58 58 0 0 1 116 0v175m53 0V175a58 58 0 0 1 116 0v175" fill="#eed5b1"/><ellipse cx="334" cy="285" rx="150" ry="30" fill="#fbecd6"/><path d="M230 304v46m206-46v46" stroke="#73523f" strokeWidth="10"/><ellipse cx="272" cy="283" rx="31" ry="12" fill="#cc9375"/><ellipse cx="387" cy="283" rx="31" ry="12" fill="#cc9375"/><path d="M333 280v-43" stroke="#567454" strokeWidth="5"/><path d="M333 254q-45-40-31-48 39 5 31 48m0-16q7-43 34-42-1 33-34 42" fill="#567454"/></> : kind === 'comedy' ? <><path d="M80 0v350m60-350v350m360-350v350m60-350v350" stroke="#71424b" strokeWidth="48"/><ellipse cx="321" cy="315" rx="168" ry="29" fill="#493c42"/><path d="M322 307V156" stroke="#ecd4bb" strokeWidth="5"/><rect x="310" y="119" width="24" height="50" rx="12" fill="#ede0c8"/><path d="m310 307 12-12 13 12" fill="none" stroke="#ecd4bb" strokeWidth="4"/><path d="m255 0 32 113h77L397 0" fill="#f5d6a7" opacity=".17"/></> : <><path d="M0 260v-50h50v-37h35v65h35v-48h60v42h30v-62h43v-35h42v97h40v-48h64v51h40v-72h46v38h61v-27h46v67h48v-37h40v96Z" fill="#b39085" opacity=".65"/><path d="M0 291v-44h77v-30h48v58h76v-52h65v66h65v-43h65v27h80v-62h59v61h105v78H0" fill="#867b77"/><path d="M0 285H640V350H0Z" fill="#5e6259"/><path d="M0 281H640" stroke="#e5c5a7" strokeWidth="8"/><path d="M0 72q280 164 640-20" fill="none" stroke="#68584e" strokeWidth="2"/>{[75,160,247,336,426,517,598].map((x,i)=><circle key={x} cx={x} cy={[102,125,139,142,130,106,75][i]} r="5" fill="#ffe9ad"/>)}<path d="m86 350 18-159q-6-17-1-32" fill="none" stroke="#464f44" strokeWidth="11"/><path d="M103 160q-62-67-92-12 45-11 89 20-50-13-77 31 50-30 80-32-17-73 34-79-25 31-27 74 59-53 87-15-51-2-87 22 61-14 82 34-48-32-82-33" fill="#46584a"/><ellipse cx="442" cy="314" rx="63" ry="10" fill="#d3ae87"/><path d="M442 318v32m-39-32-17 32m95-32 17 32" stroke="#dbc19c" strokeWidth="5"/></>}
    <rect width="640" height="350" fill={`url(#grain-${kind})`}/>
  </svg></div>;
}
function App() {
  const [state, setState] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [fatal, setFatal] = useState(false);
  const [tab, setTab] = useState('chat'), [persona, setPersona] = useState('host'), [busy, setBusy] = useState(false), [text, setText] = useState('');
  const [modal, setModal] = useState(null), [toast, setToast] = useState(''), [name, setName] = useState(''), [selected, setSelected] = useState(['Mike','Dave']), [customName, setCustomName] = useState('');
  const [suggestion, setSuggestion] = useState(''), [reason, setReason] = useState(''), [showConversion, setShowConversion] = useState(false), [conversionDismissed, setConversionDismissed] = useState(false);
  const [guestView, setGuestView] = useState(null), [drawer, setDrawer] = useState(false);
  const chatEnd = useRef(null), composer = useRef(null), modalRef = useRef(null), modalTrigger = useRef(null), mutationEpoch = useRef(0);
  const person = state?.plan.participants.find(p => p.id === (guestToken ? state.guestId : persona));
  const isHost = !guestToken && persona === 'host';
  const viewed = guestToken ? state : isHost ? state : guestView;
  const plan = state?.plan, events = state?.events || [], event = events.find(e => e.id === state?.recommendation), firstStop = events.find(e => e.id === plan?.stops[0]);
  const endpoint = guestToken ? `/api/guest/${guestToken}` : '/api/state';
  useEffect(() => { api(endpoint).then(setState).catch(e => { if(e.status !== 401 || guestToken) { setError(e.message); setFatal(true); } }).finally(() => setLoading(false)); }, []);
  useEffect(() => {
    if (!state) return; let active = true;
    const timer = setInterval(() => { const epoch = mutationEpoch.current; api(endpoint).then(s => { if(active && epoch === mutationEpoch.current) setState(prev => prev?.id === s.id && prev.revision >= s.revision ? prev : s); }).catch(e => { if(active && epoch === mutationEpoch.current) setError(e.message); }); }, 3000);
    return () => { active = false; clearInterval(timer); };
  }, [!!state]);
  useEffect(() => { if (isHost || guestToken || !person) { setGuestView(null); return; } let active=true; api(`/api/guest/${person.invite}`).then(s=>{if(active)setGuestView(s);}).catch(e=>setError(e.message)); return()=>{active=false;}; }, [persona, state?.revision]);
  useEffect(() => { const pane = chatEnd.current?.parentElement; if (pane) pane.scrollTo({ top: pane.scrollHeight, behavior: 'instant' }); }, [state?.messages?.length, tab, persona]);
  useEffect(() => { if (!toast) return; const timer=setTimeout(()=>setToast(''),3500); return()=>clearTimeout(timer); },[toast]);
  useEffect(() => {
    if (!modal) return;
    modalTrigger.current = document.activeElement;
    const focusTimer=setTimeout(()=>modalRef.current?.querySelector('button,input,select')?.focus(),10);
    const key=e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=[...modalRef.current.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    document.addEventListener('keydown',key); return()=>{clearTimeout(focusTimer);document.removeEventListener('keydown',key);modalTrigger.current?.focus();};
  }, [modal]);
  async function run(fn) { mutationEpoch.current++; setBusy(true); setError(''); try { return await fn(); } catch(e) { setError(e.message); return null; } finally { mutationEpoch.current++; setBusy(false); } }
  async function act(action, data={}) {return run(async()=>{const next=await api('/api/action',{action,...data});setState(next);return next;});}
  async function guestAct(action, data={}) {
    return run(async()=>{ const next=await api(`/api/guest/${guestToken || person.invite}`,{action,...data}); if(guestToken)setState(next);else{setGuestView(next);setState(await api('/api/state'));}return next; });
  }
  async function send(e) {
    e.preventDefault(); if (!text.trim() || busy) return;
    const value=text;setText('');
    const result = isHost ? await run(async()=>{const s=await api('/api/chat',{text:value});setState(s);return s;}) : await guestAct('text',{text:value.trim()});
    if(!result)setText(value);else if(!isHost)setToast(/^help$/i.test(value)?'Reply YES, MAYBE, NO or STOP. This demo sends no real texts.':/^stop$/i.test(value)?'Demo messages stopped.':'Text reply simulated. Your plan is up to date.');
    composer.current?.focus();
  }
  async function rsvp(response) {const result=await guestAct('rsvp',{response});if(result&&response==='yes'&&!conversionDismissed)setShowConversion(true);}
  async function copy(value) {try{await navigator.clipboard.writeText(value);setToast('Link copied. Good plans travel.');}catch{setToast('Copy the link from the field below.');}}
  const friendPicker = <div className="friend-picker"><div className="eyebrow">GOOD COMPANY MAKES THE PLAN</div><h3>Who’s coming with you?</h3><div className="friend-options">{['Mike','Dave','Sarah',...selected.filter(x=>!['Mike','Dave','Sarah'].includes(x))].map((n,i)=><button key={n} className={`friend-option ${selected.includes(n)?'selected':''}`} onClick={()=>setSelected(prev=>prev.includes(n)?prev.filter(x=>x!==n):[...prev,n])} aria-pressed={selected.includes(n)}><Avatar name={n} index={i}/>{n}{selected.includes(n)&&<Check size={14}/>}</button>)}</div><form className="add-friend" onSubmit={e=>{e.preventDefault();if(customName.trim()){setSelected([...new Set([...selected,customName.trim()])]);setCustomName('');}}}><input aria-label="Friend’s name" value={customName} maxLength={40} onChange={e=>setCustomName(e.target.value)} placeholder="Someone else? Add a name"/><button aria-label="Add friend" disabled={!customName.trim()}><Plus size={18}/></button></form><button className="button primary full" disabled={busy||!selected.length} onClick={async()=>{if(await act('invite',{names:selected})){setTab('page');setModal('share');}}}>Create the plan page <ArrowRight size={16}/></button><p className="fine">Personal links only. No messages are sent.</p></div>;
  function recommendation(e, compact=false) {return <article className={`event-card ${compact?'compact':''}`}><Illustration kind={e.color}/><div className="event-content"><div className="event-kicker"><span><MapPin size={12}/>{e.area}</span><span>{e.priceText||(e.price?`$${e.price} / person`:'Free')}</span></div><h3>{e.title}</h3><p>{e.tag}</p><div className="event-meta"><CalendarDays size={14}/>{e.time}</div><div className="event-meta"><MapPin size={14}/>{e.venue}</div>{!compact&&<button className="button primary full" disabled={busy||plan.status!=='proposed'} onClick={()=>act('accept',{eventId:e.id})}>Make this the plan <ArrowUpRight size={16}/></button>}<span className="fixture-note">Curated demo · sample event</span></div></article>;}
  if(loading) return <div className="loading-screen"><Mark/><p>Making room for good plans…</p><LoaderCircle className="spin"/></div>;
  if(fatal) return <div className="loading-screen"><Mark/><h1>This link needs a little help.</h1><p>{error}</p><a className="button primary" href="/">Start your own Rall-e</a></div>;
  if(!state) return <Onboarding api={api} busy={busy} error={error} onSignedIn={setState} onStart={(name,verification)=>run(async()=>setState(await api('/api/session',{name,...(verification?{verification}:{})})))}/>;
  if(!isHost && viewed) return <GuestPage state={viewed} onAction={guestAct} busy={busy} error={error} renderArt={kind=><Illustration kind={kind}/>} onBack={!guestToken?()=>setPersona('host'):null}/>;

  return <div className="app-shell sms-first-preview">
    <aside className={`sidebar ${drawer?'open':''}`}><a href="/" className="brand"><Wordmark/></a><p className="brand-caption">Good plans. Better company.</p><div className="workspace-label">YOUR LITTLE CORNER</div><button className={`side-nav ${tab==='chat'?'active':''}`} onClick={()=>{setTab('chat');setDrawer(false);}}><MessageCircle size={18}/>{guestToken?'Your invitation':'Chat with Rall-e'}<span className="nav-dot"/></button><button className={`side-nav ${tab==='page'?'active':''}`} onClick={()=>{setTab('page');setDrawer(false);}}><CalendarDays size={18}/>The plan page{plan.stops.length>0&&<span className="count">1</span>}</button>{!guestToken&&<button className="side-nav" onClick={()=>setModal('preferences')}><Heart size={18}/>Getting to know you</button>}<div className="side-divider"/><div className="side-note"><Sun size={25} strokeWidth={1.3}/><h3>Make a little more<br/>of your weekend.</h3><p>The best plans start with<br/>“why not?”</p></div><div className="sidebar-bottom"><span className="location-label"><MapPin size={15}/> Hollywood, Los Angeles</span><div className="profile"><Avatar name={guestToken?person?.name||'Guest':state.name}/><div><strong>{guestToken?person?.name:state.name}</strong><span>{guestToken?'Your personal invitation':'Your weekend starts here'}</span></div>{!guestToken&&<button className="icon-button" aria-label="Demo controls" onClick={()=>setModal('demo')}><Settings2 size={17}/></button>}</div></div></aside>
    {drawer&&<button className="drawer-overlay" aria-label="Close navigation" onClick={()=>setDrawer(false)}/>}
    <div className="app-main"><div className="presenter-preview-note"><MessageCircle size={14}/><span>SMS conversation preview</span><small>The Rall-e experience happens by text. This browser view is for the demo.</small></div><header className="topbar"><button className="mobile-brand" onClick={()=>setDrawer(!drawer)} aria-label="Open navigation"><Wordmark/></button><div className="breadcrumb">YOUR WEEKEND <ChevronRight size={12}/><span>{isHost?'A plan in the making':`${state.name}’s invitation`}</span></div><div className="topbar-right"><span className="live-label"><span/>A LITTLE DEMO, A LOT OF POSSIBILITY</span><button className="icon-button" aria-label="About this demo" onClick={()=>setModal('about')}><CircleHelp size={18}/></button></div></header>
    <main className="workspace"><div className="page-heading"><div><div className="eyebrow">{isHost?'LESS PLANNING. MORE LIVING.':'GOOD COMPANY STARTS WITH YOU.'}</div><h1>{isHost?'Let’s make something happen.':`${state.name} has a plan for you.`}</h1><p>{isHost?'A good idea, your favorite people, and a little help getting there.':'One good plan. One shared page. All that’s missing is you.'}</p></div><span className="weekend-badge"><Sun size={19}/> THE WEEKEND EDIT</span></div>
    <div className="workspace-toolbar"><div className="tabs" role="tablist" aria-label="Plan views"><button role="tab" aria-selected={tab==='chat'} className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}><MessageCircle size={16}/>{isHost?'Chat with Rall-e':'Texts'}{tab==='chat'&&<span className="tiny-dot"/>}</button><button role="tab" aria-selected={tab==='page'} className={tab==='page'?'active':''} onClick={()=>setTab('page')}><Frame size={16}/>The page{plan.stops.length>0&&<span className="tab-count">{1+plan.participants.filter(p=>p.response==='yes').length} in</span>}</button></div>{!guestToken&&<label className="persona-picker"><span>Preview as</span><select aria-label="Preview as" value={persona} onChange={e=>{setPersona(e.target.value);setText('');setShowConversion(false);}}><option value="host">{state.name} · Host</option>{plan.participants.map(p=><option key={p.id} value={p.id}>{p.name} · Guest</option>)}</select></label>}</div>
    {error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    <div className={`content-grid ${tab==='page'?'plan-layout':''}`}>
      <section className="primary-panel">
        {tab==='chat'?<div className="chat-panel"><div className="chat-header"><Mark/><div><strong>{isHost?'Rall-e':'Your texts with Rall-e'}</strong><span>{isHost?'A little nudge toward a good time':'SMS + image preview · nothing is sent'}</span></div><span className="online-dot"/></div><div className="messages" role="log" aria-label="Conversation">
        <div className="chat-date">{isHost?'YOUR NEXT GOOD STORY STARTS HERE':'A PLAN FROM '+state.name.toUpperCase()}</div>
        {isHost?state.messages.map(m=><div key={m.id} className={`message ${m.role}`}><div className="bubble">{m.text}</div>{m.eventId&&events.find(e=>e.id===m.eventId)&&recommendation(events.find(e=>e.id===m.eventId))}<span className="message-label">{m.role==='assistant'?'Rall-e':'You'}</span></div>):<><div className="message assistant"><div className="bubble">Hey {person?.name}! {state.name} wants to get everyone together for {firstStop?.short||'a Saturday outing'}. {firstStop?.time}. Are you in? Reply YES, MAYBE, or NO, or open the page to see the plan.</div>{firstStop&&<div className="mms-image"><Illustration kind={firstStop.color}/><span>MMS image preview</span></div>}<button className="text-link" onClick={()=>setTab('page')}>View your personal plan page <ArrowUpRight size={14}/></button><span className="message-label">Invitation preview · not sent</span></div>{person?.response!=='pending'&&<><div className="message user"><div className="bubble">{person?.response.toUpperCase()}</div></div><div className="message assistant"><div className="bubble">{person?.response==='yes'?`You’re in! ${state.name}’s page is up to date. Can’t wait to get the group together.`:person?.response==='maybe'?'A maybe it is. You can change your answer on the page anytime.':'No worries. Your host can see you can’t make it.'}</div></div></>}{person?.stopped&&<div className="message assistant"><div className="bubble">You’ve opted out of demo messages. You can still use the page.</div></div>}</>}
        {busy&&<div className="typing" aria-label="Working"><i/><i/><i/></div>}
        {isHost&&state.stage==='location'&&<div className="quick-replies"><button disabled={busy} onClick={()=>act('location')}><MapPin size={15}/>Yes, Hollywood <ArrowRight size={14}/></button></div>}
        {isHost&&state.stage==='vibe'&&<div className="quick-replies vibes">{Object.entries(vibeIcons).map(([v,Icon])=><button key={v} disabled={busy} onClick={()=>act('vibe',{category:v})}><Icon size={15}/>{v==='nature'?'Something outdoors':v[0].toUpperCase()+v.slice(1)}</button>)}</div>}
        {isHost&&state.stage==='discover'&&plan.status==='proposed'&&<div className="quick-replies"><button disabled={busy} onClick={()=>act('alternative')}>What else is out there? <RotateCcw size={13}/></button><button onClick={()=>{setText('When do doors open?');composer.current?.focus();}}>When do doors open?</button></div>}
        {isHost&&state.stage==='invite'&&friendPicker}
        {isHost&&state.stage==='planning'&&<div className="quick-replies"><button onClick={()=>setTab('page')}>See the plan <ArrowUpRight size={14}/></button><button onClick={()=>setModal('share')}><Link size={14}/>Share with friends</button></div>}
        {!isHost&&<div className="quick-replies">{['YES','MAYBE','NO'].map(v=><button key={v} disabled={busy} onClick={async()=>{if(await guestAct('text',{text:v}))setToast('Reply simulated. The shared page is updated.');}}>{v}</button>)}</div>}
        <div ref={chatEnd}/></div><form className="composer" onSubmit={send}><input ref={composer} aria-label={isHost?'Message Rall-e':'Simulate text reply'} placeholder={isHost?'Tell me what you’re in the mood for…':'Try YES, MAYBE, NO, STOP, or HELP…'} value={text} maxLength={1000} onChange={e=>setText(e.target.value)}/><button aria-label="Send message" disabled={busy||!text.trim()}><ArrowUp size={20}/></button></form><div className="composer-note"><span><Sparkles size={11}/>{state.aiMode==='bedrock'?'Conversation powered by Bedrock':state.aiMode==='fallback'?'AI unavailable · curated fallback':'Curated conversation demo'}</span><span>Your next “remember when” awaits.</span></div></div>
        :!plan.stops.length?<div className="empty-plan"><Compass size={42} strokeWidth={1}/><h2>A good plan is just<br/>a conversation away.</h2><p>Start with a vibe. We’ll find the idea,<br/>then bring your people into it.</p><button className="button primary" onClick={()=>setTab('chat')}>Find your weekend <ArrowRight size={16}/></button></div>:<div className="plan-page"><Illustration kind={firstStop.color} className="plan-cover"/><div className="plan-body"><div className="plan-topline"><span className={`status ${plan.status}`}><span/>{({proposed:'A plan in the making',confirmed:'It’s happening',happened:'One for the memories',dropped:'Plan closed'})[plan.status]}</span><span className="sample-label">SAMPLE OUTING</span></div><h2>{plan.title}</h2><p className="plan-subtitle">A little escape from the everyday, together.</p><div className="host-line"><Avatar name={state.name} small/><span>Planned by <strong>{state.name}</strong></span><span>·</span><span>Hollywood, LA</span></div><div className="plan-facts"><span><CalendarDays size={17}/>This Saturday</span><span><Users size={17}/>{1+plan.participants.filter(p=>p.response==='yes').length} going</span><span>{plan.mode==='loose'?<Sparkles size={16}/>:<LockKeyhole size={16}/>} {plan.mode==='loose'?'Open to ideas':'Locked itinerary'}</span></div>
        <div className="section-heading"><h3>The little itinerary</h3>{isHost&&plan.status==='proposed'&&plan.stops.length<state.limits.stops&&<button className="text-link" onClick={()=>setModal('addStop')}><Plus size={14}/>Add a stop</button>}</div><div className="itinerary">{plan.stops.map((id,i)=>{const e=events.find(x=>x.id===id);return <article key={id} className="stop"><span className="stop-number">{i+1}</span><div><span className="stop-time">{e.time.split('·')[1]}</span><h4>{e.short}</h4><p>{e.venue} · {e.area}</p><div className="stop-details"><span><Clock3 size={13}/>{e.duration}</span><span>{e.priceText||(e.price?`$${e.price} / person`:'Free')}</span><span>{e.age}</span></div><p className="stop-description">{e.description}</p><details><summary>Good to know</summary><p>Doors / arrival: {e.doors}. {e.accessibility} Fictional sample venue; no booking or live availability.</p></details></div>{isHost&&plan.status==='proposed'&&plan.stops.length>1&&<button className="icon-button" aria-label={`Remove ${e.short}`} onClick={()=>act('removeStop',{eventId:id})}><X size={15}/></button>}</article>;})}</div>
        <div className="section-heading"><h3>The good company</h3>{isHost&&<button className="text-link" onClick={()=>setModal('share')}><Link size={14}/>Invite links</button>}</div><div className="people"><div className="person-row"><Avatar name={state.name}/><span><strong>{state.name}</strong><small>Making it happen</small></span><span className="rsvp-status yes">Host</span></div>{plan.participants.map((p,i)=><div className="person-row" key={p.id}><Avatar name={p.name} index={i+1}/><span><strong>{p.name}{p.id===person?.id?' (you)':''}</strong><small>{p.response==='pending'?'An open invitation':'A little closer to a plan'}</small></span><span className={`rsvp-status ${p.response}`}>{({yes:'I’m in',maybe:'Maybe',no:'Can’t make it',pending:'Awaiting reply'})[p.response]}</span></div>)}</div>
        {!isHost&&<div className="response-card"><h3>Save you a spot?</h3><p>Your answer updates the plan for everyone.</p><div className="rsvp-buttons">{[['yes','I’m in'],['maybe','Maybe'],['no','Can’t']].map(([value,label])=><button key={value} disabled={busy||['happened','dropped'].includes(plan.status)} className={`button ${person?.response===value?'primary':'secondary'}`} onClick={()=>rsvp(value)}>{value==='yes'&&<Check size={16}/>} {label}</button>)}</div><label className="consent"><input type="checkbox" checked={Boolean(person?.consent)} disabled={busy||person?.stopped} onChange={e=>guestAct('consent',{enabled:e.target.checked})}/><span>Keep me posted about this plan by text.<small>Optional demo preference. No real messages sent. Reply STOP to opt out.</small></span></label></div>}
        {plan.mode==='loose'&&<><div className="section-heading"><h3>A little room for other ideas</h3><span className="muted">{plan.suggestions.length} ideas</span></div>{plan.suggestions.length?plan.suggestions.map(s=>{const e=events.find(x=>x.id===s.eventId);return <div className="suggestion" key={s.id}><div><span className="eyebrow">{s.name} SUGGESTED</span><h4>{e.short}</h4><p>{s.reason||e.tag}</p></div>{isHost?<button className="button secondary" disabled={busy||plan.status!=='proposed'} onClick={()=>act('selectSuggestion',{id:s.id})}>Choose idea ({s.votes.length})</button>:<button className={`vote ${s.votes.includes(person?.id)?'selected':''}`} aria-label={`Vote for ${e.short}`} disabled={busy||plan.status!=='proposed'} onClick={()=>guestAct('vote',{id:s.id})}><ThumbsUp size={15}/>{s.votes.length}</button>}</div>;}):<p className="suggestion-empty">A different spot? A better idea? This is where everyone weighs in.</p>}{!isHost&&plan.status==='proposed'&&<button className="button secondary full" onClick={()=>{setSuggestion(events.find(e=>!plan.stops.includes(e.id))?.id||'');setModal('suggest');}}><Plus size={16}/>Suggest another idea</button>}</>}
        {isHost&&<div className="host-actions">{plan.status==='proposed'&&<><div className="mode-control"><span>Let friends suggest ideas</span><button role="switch" aria-checked={plan.mode==='loose'} aria-label="Let friends suggest ideas" className={`toggle ${plan.mode==='loose'?'on':''}`} disabled={busy} onClick={()=>act('mode',{mode:plan.mode==='loose'?'locked':'loose'})}><i/></button></div><button className="button primary full" disabled={busy} onClick={()=>setModal('confirm')}>Let’s make it official <Check size={16}/></button></>}{plan.status==='confirmed'&&<><div className="confirmed-panel"><CheckCircle2 size={20}/><span>It’s happening. Your friends can see the confirmed plan.</span></div><button className="button secondary full" onClick={()=>setModal('update')}><MessageCircle size={16}/>Preview the group update</button><button className="text-link" disabled={busy} onClick={()=>act('happened')}>We went! Mark as happened <ArrowRight size={14}/></button></>}{['proposed','confirmed'].includes(plan.status)&&<button className="text-link muted" onClick={()=>setModal('drop')}>Drop this plan</button>}</div>}<p className="fine plan-disclosure">Made with Rall-e · All outings, prices, and availability are sample data. No bookings or payments.</p></div></div>}
      </section>
      <aside className="context-panel"><div className="context-eyebrow"><span className="tiny-dot"/> YOUR WEEKEND, COMING TOGETHER</div>{(firstStop||event)?<div className="plan-peek"><div className="peek-art"><Illustration kind={(firstStop||event).color}/><span className="image-label">A LITTLE SOMETHING TO LOOK FORWARD TO</span></div><div className="peek-content"><span className="eyebrow">{firstStop?'THE PLAN SO FAR':'PICKED FOR YOUR MOOD'}</span><h2>{(firstStop||event).short}</h2><p>{(firstStop||event).tag}</p><div className="peek-detail"><CalendarDays size={15}/>{(firstStop||event).time}</div><div className="peek-detail"><MapPin size={15}/>{(firstStop||event).venue}</div>{firstStop&&<><div className="peek-people"><div className="avatar-stack"><Avatar name={state.name} small/>{plan.participants.slice(0,3).map((p,i)=><Avatar key={p.id} name={p.name} small index={i+1}/>)}</div><span>{1+plan.participants.filter(p=>p.response==='yes').length} in · {plan.participants.filter(p=>p.response==='pending').length} to hear from</span></div><button className="button secondary full" onClick={()=>setTab('page')}>See the shared page <ArrowUpRight size={15}/></button></>}</div></div>:<div className="wide-open"><Illustration kind="rooftop"/><div><span className="eyebrow">THE POSSIBILITIES ARE PRETTY GOOD</span><h2>Your weekend<br/>is wide open.</h2><p>Something new around the corner.<br/>Someone you’ve been meaning to see.<br/>Let’s bring the two together.</p><div className="little-stars">✧ <span>✳</span> ✧</div></div></div>}
      <div className="how-card"><span className="eyebrow">A LITTLE LESS BACK-AND-FORTH</span><div><span className={`step-dot ${state.stage!=='location'?'done':''}`}>1</span><p><strong>Find your kind of thing</strong><span>A good recommendation gets us going.</span></p></div><div><span className={`step-dot ${plan.participants.length?'done':''}`}>2</span><p><strong>Bring your people in</strong><span>One link. No app. Everyone’s included.</span></p></div><div><span className={`step-dot ${plan.status==='confirmed'?'done':''}`}>3</span><p><strong>Less planning. More showing up.</strong><span>One page keeps it all together.</span></p></div></div>
      {isHost&&<div className="nudge-card"><Bell size={18}/><div><strong>Your next good idea, on us.</strong><p>A little nudge before the weekend?</p><label><input type="checkbox" checked={state.recurring} disabled={busy||state.stopped} onChange={e=>act('recurring',{enabled:e.target.checked})}/> Keep the ideas coming</label></div></div>}
      {plan.activity?.length>0&&null}<p className="side-footnote">A prototype for more real-life connection.<br/>Curated events. Simulated texts. Real possibility.</p></aside>
    </div><footer className="workspace-footer"><span>GO MAKE A GOOD STORY.</span><button onClick={()=>setModal(guestToken?'about':'demo')}><Settings2 size={13}/>{guestToken?'About this demo':'Presenter controls'}</button></footer></main></div>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
    {showConversion&&<div className="conversion"><button className="icon-button" aria-label="Dismiss Rall-e invitation" onClick={()=>{setShowConversion(false);setConversionDismissed(true);}}><X size={17}/></button><Mark/><h3>Your people. Your next plan.</h3><p>You’re in. Why not make something happen for your own group next?</p><a className="button primary" href="/" onClick={()=>{if(!guestToken){setShowConversion(false);setPersona('host');setTab('chat');}}}>Try Rall-e <ArrowRight size={15}/></a><button className="text-link" onClick={()=>{setShowConversion(false);setConversionDismissed(true);}}>Not now</button></div>}
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><section className="modal" ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button>
      {modal==='share'&&<><span className="eyebrow">GOOD PLANS TRAVEL</span><h2 id="modal-title">Bring your people in.</h2><p>Each friend gets a personal link. No app, no account, no endless group chat.</p>{plan.participants.map((p,i)=><div className="share-person" key={p.id}><div><Avatar name={p.name} index={i+1}/><strong>{p.name}</strong><span className="muted">{p.response==='pending'?'Ready to share':p.response}</span></div><div className="share-link"><input readOnly aria-label={`${p.name}’s invitation link`} value={`${location.origin}/p/${p.invite}`} onFocus={e=>e.target.select()}/><button className="icon-button" aria-label={`Copy ${p.name} link`} onClick={()=>copy(`${location.origin}/p/${p.invite}`)}><Copy size={16}/></button><a className="icon-button" aria-label={`Open ${p.name} invitation`} href={`/p/${p.invite}`} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></div></div>)}{!plan.participants.length&&friendPicker}<p className="fine">Links expire after 7 days. These are personal invitations: share each link only with its intended friend. No texts have been sent.</p></>}
      {modal==='preferences'&&<><span className="eyebrow">A LITTLE MORE YOU, EVERY TIME</span><h2 id="modal-title">Getting to know you.</h2><p>Every “love it,” “not my thing,” and outing helps shape your next recommendation.</p>{Object.keys(state.preferences).length?Object.entries(state.preferences).map(([category,score])=><div className="preference-row" key={category}><span>{category}</span><span className="preference-meter"><i style={{width:`${Math.max(8,Math.min(100,(score+2)*16))}%`}}/></span><small>{score>0?'More like this':score<0?'Less like this':'Still exploring'}</small></div>):<div className="simple-empty">A fresh start. React to an idea and your preferences will start to grow.</div>}<div className="memory-note"><Users size={20}/><span>{plan.participants.length?`You’ve included ${plan.participants.map(x=>x.name).join(', ')} in this plan. Their responses stay with your shared plan.`:'Bring a few friends into a plan to start building your circle.'}</span></div><p className="fine">Simple saved preference scores for this demo. No inferred interests are assigned to your friends without their reactions.</p></>}
      {modal==='demo'&&<><span className="eyebrow">BEHIND THE DEMO</span><h2 id="modal-title">A little nudge, on cue.</h2><p>Preview the moments that would normally arrive by text. These controls are for the presenter; no real messages are sent.</p><button className="demo-action" disabled={busy||!state.recurring||state.stopped||state.nudges.includes('weekend')} onClick={async()=>{if(await act('nudge',{kind:'weekend'})){setModal(null);setPersona('host');setTab('chat');}}}><Sun/><span><strong>It’s almost the weekend</strong><small>{state.recurring?'Preview a recommendation based on your reactions':'Opt in to weekend ideas using the checkbox first'}</small></span><ArrowRight size={18}/></button><button className="demo-action" disabled={busy||!plan.stops.length||plan.status!=='proposed'||state.nudges.includes('followup')||state.stopped} onClick={async()=>{if(await act('nudge',{kind:'followup'})){setModal(null);setPersona('host');setTab('chat');}}}><Bell/><span><strong>Give an unfinished plan a nudge</strong><small>Follow up while the plan is still proposed</small></span><ArrowRight size={18}/></button><button className="demo-action" onClick={()=>setModal('reset')}><RotateCcw/><span><strong>Start this demo over</strong><small>Reset only this browser’s plan and its invitation links</small></span><ArrowRight size={18}/></button><div className="activity-list"><h3>What’s happened</h3>{state.activity.slice(0,5).map(a=><p key={a.id}><span/>{a.text}</p>)}{!state.activity.length&&<p>The next good story is still ahead.</p>}</div></>}
      {modal==='demo'&&<label className="consent"><input type="checkbox" checked={state.recurring} disabled={busy||state.stopped} onChange={e=>act('recurring',{enabled:e.target.checked})}/><span>Keep the weekend ideas coming<small>Opt in to recommendation previews. Nothing is sent.</small></span></label>}
      {!guestToken && ['demo','share','update'].includes(modal) && <button className="button secondary full sms-entry" onClick={()=>setModal('sms')}><Send size={16}/>Text approved testers</button>}
      {modal==='sms' && !guestToken && <SmsPanel plan={plan}/>}
      {modal==='about'&&<><span className="eyebrow">PROTOTYPE, WITH PURPOSE</span><h2 id="modal-title">A feel for what’s possible.</h2><p>Your plan, replies, votes, and preferences are saved and shared across the views. Events and illustrations are curated fictional samples. The on-screen Texts view, MMS, and scheduled nudges are simulations. Presenter texting can send invitations and confirmations to approved testers when Twilio is enabled.</p><p>{state.aiMode==='bedrock'?'Live conversational wording is connected through AWS Bedrock.':'Conversation currently uses a small local demo engine. Live AI can be connected through AWS Bedrock.'} Booking and payments are outside this demo.</p><p className="fine">Hollywood, Los Angeles is the demo locale, not an IP-detected location.</p></>}
      {modal==='addStop'&&<><h2 id="modal-title">Make a little more of it.</h2><p>Add up to {state.limits.stops} stops to this outing. Times are samples; keep travel and timing in mind.</p><div className="event-choices">{events.filter(e=>!plan.stops.includes(e.id)).map(e=><button key={e.id} disabled={busy} onClick={async()=>{if(await act('addStop',{eventId:e.id}))setModal(null);}}><Illustration kind={e.color}/><span><strong>{e.short}</strong><small>{e.time} · {e.priceText||(e.price?`$${e.price}`:'Free')}</small></span><Plus size={18}/></button>)}</div></>}
      {modal==='suggest'&&<><h2 id="modal-title">Got another idea?</h2><p>One idea per person keeps the group chat from becoming, well, a group chat. A new suggestion replaces your previous one.</p><form onSubmit={async e=>{e.preventDefault();if(await guestAct('suggest',{eventId:suggestion,reason})){setModal(null);setReason('');}}}><label htmlFor="suggestion">Your idea</label><select id="suggestion" value={suggestion} onChange={e=>setSuggestion(e.target.value)}>{events.filter(e=>!plan.stops.includes(e.id)).map(e=><option key={e.id} value={e.id}>{e.short}</option>)}</select><label htmlFor="reason">A little pitch (optional)</label><textarea id="reason" placeholder="Feels like our kind of Saturday…" value={reason} onChange={e=>setReason(e.target.value)} maxLength={200}/><button className="button primary full" disabled={busy||!suggestion}>Put it to the group <ArrowRight size={16}/></button></form></>}
      {modal==='confirm'&&<><h2 id="modal-title">See you there?</h2><p>Confirm “{plan.title}” for your group. {plan.participants.filter(p=>p.response==='pending').length} friends are still to reply; they can RSVP after you confirm.</p><p>This confirms your shared plan. It doesn’t book a venue or send a text.</p><button className="button primary full" disabled={busy} onClick={async()=>{if(await act('confirm'))setModal(null);}}>Confirm the plan <Check size={16}/></button></>}
      {modal==='update'&&<><h2 id="modal-title">The “it’s happening” text.</h2><span className="pill">PREVIEW ONLY · NOT SENT</span><div className="preview-bubble">It’s a plan! {state.name} has confirmed {plan.title}. {plan.stops.map(id=>{const e=events.find(x=>x.id===id);return `${e.short} at ${e.time.split('·')[1].trim()}.`;}).join(' ')} Check your personal page for everyone’s latest responses. See you there!</div><p>Only guests who explicitly opt in could receive future plan texts. These previews send nothing. Approved testers can receive a real text through presenter texting.</p><div className="recipient-list">{plan.participants.map(p=><p key={p.id}><strong>{p.name}</strong><span>{p.stopped?'Opted out':p.consent?'Opted in to this plan':'Link only · no SMS consent'}</span></p>)}</div></>}
      {modal==='reset'&&<><h2 id="modal-title">A fresh weekend?</h2><p>This removes your demo plan, conversation, and preferences. Its existing guest links will stop working. Other demos aren’t affected.</p><button className="button primary full" disabled={busy} onClick={()=>run(async()=>{setState(await api('/api/reset',{}));setPersona('host');setTab('chat');setModal(null);setShowConversion(false);setError('');})}>Reset this demo <RotateCcw size={16}/></button></>}
      {modal==='drop'&&<><h2 id="modal-title">Another time, then?</h2><p>Close this plan for the whole group. Their shared page will show that it’s been dropped. No messages will be sent.</p><button className="button primary full" disabled={busy} onClick={async()=>{if(await act('drop'))setModal(null);}}>Drop the plan</button></>}
    </section></div>}
  </div>;
}
const inviteCode = /^\/i\/([a-z0-9-]{8,64})$/.exec(location.pathname)?.[1] || '';
// Invite-only: the home page is the waitlist / invite front door (no web chat); plans and pages still open from their links.
createRoot(document.getElementById('root')).render(location.pathname.startsWith('/me/') ? <MePage token={location.pathname.split('/')[2] || ''}/> : !guestToken && !/^\/(ops|lab|v|l|s|n|e)(\/|$)/.test(location.pathname) ? <Onboarding invite={inviteCode} api={api}/> : location.pathname.startsWith('/ops') ? <OpsPage/> : location.pathname.startsWith('/lab') ? <SmsLab/> : location.pathname.startsWith('/v/') ? <VaultPage token={location.pathname.split('/')[2] || ''}/> : location.pathname.startsWith('/l/') ? <LocationPage token={location.pathname.split('/')[2] || ''}/> : location.pathname.startsWith('/s/') ? <SharePage token={location.pathname.split('/')[2] || ''} renderArt={kind => <Illustration kind={kind}/>}/> : location.pathname.startsWith('/n/') ? <NightPage token={location.pathname.split('/')[2] || ''} renderArt={kind => <Illustration kind={kind}/>}/> : location.pathname.startsWith('/e/') ? <EventPage id={location.pathname.split('/')[2] || ''} renderArt={kind => <Illustration kind={kind}/>}/> : <App/>);
